name: download-artifact

description: Download Artifact

inputs:
  platform:
    description: Platform
    required: true
  python_version:
    description: Python version
    required: true
  debug:
    description: Enable debug logging
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.platform }}_python-${{ inputs.python_version }}${{ inputs.debug == 'true' && '_debug' || '' }}
        path: ${{ inputs.debug == 'true' && 'dist_debug/' || '' }}${{ inputs.platform }}_python-${{ inputs.python_version }}${{ inputs.debug == 'true' && '_debug' || '' }}
      env:
        ACTIONS_STEP_DEBUG: ${{ inputs.debug }}
    - name: Append path to package_paths.env
      shell: bash
      run: |
        DOWNLOAD_DIR="${{ inputs.debug == 'true' && 'dist_debug/' || '' }}${{ inputs.platform }}_python-${{ inputs.python_version }}${{ inputs.debug == 'true' && '_debug' || '' }}"
        PACKAGE_NAME=$(basename `ls -1 "$DOWNLOAD_DIR"/*.whl`)
        mv "$DOWNLOAD_DIR"/*.whl ./
        echo "$PACKAGE_NAME" >> package_paths.env
