name: download-artifact

description: Download Artifact

inputs:
  platform:
    description: Platform
    required: true
  python_version:
    description: Python version
    required: true
  debug:
    description: Enable debug logging
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Download artifact (release)
      if: inputs.debug == 'false'
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.platform }}_python-${{ inputs.python_version }}
        path: ${{ inputs.platform }}_python-${{ inputs.python_version }}
      env:
        ACTIONS_STEP_DEBUG: false

    - name: Download artifact (debug)
      if: inputs.debug == 'true'
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.platform }}_python-${{ inputs.python_version }}${{ !contains(inputs.python_version, '+debug') && '_debug' || '' }}
        path: dist_debug/${{ inputs.platform }}_python-${{ inputs.python_version }}${{ !contains(inputs.python_version, '+debug') && '_debug' || '' }}
      env:
        ACTIONS_STEP_DEBUG: true

    - name: Append path to package_paths.env (release)
      if: inputs.debug == 'false'
      shell: bash
      run: |
        DOWNLOAD_DIR="${{ inputs.platform }}_python-${{ inputs.python_version }}"
        PACKAGE_NAME=$(basename `ls -1 "$DOWNLOAD_DIR"/*.whl`)
        mv "$DOWNLOAD_DIR"/*.whl ./
        echo "$PACKAGE_NAME" >> package_paths.env

    - name: Append path to package_paths.env (debug)
      if: inputs.debug == 'true'
      shell: bash
      run: |
        DOWNLOAD_DIR="dist_debug/${{ inputs.platform }}_python-${{ inputs.python_version }}${{ !contains(inputs.python_version, '+debug') && '_debug' || '' }}"
        PACKAGE_NAME=$(basename `ls -1 "$DOWNLOAD_DIR"/*.whl`)
        mv "$DOWNLOAD_DIR"/*.whl ./
        echo "$PACKAGE_NAME" >> package_paths.env
